version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    ports:
      - 1234:1234
    volumes:
      - ./server:/app/server
    command: nodemon --watch /app/server --ext py --exec python /app/server/server.py
    tty: true
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: fsmap
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    tty: true
